apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  annotations:
    consul.hashicorp.com/service-name: flask-app
    consul.hashicorp.com/service-port: "5000"
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
